pipeline {
    agent any

    stages {
        stage ("Checkout") {
            steps {
                git url: 'https://github.com/3nu3l/nodejs-rest-api-example.git', branch: 'master'
            }
        }
        stage ("Docker Build") {
            steps {
                sh 'docker build -t 781013578291.dkr.ecr.us-east-1.amazonaws.com/curso-edit-backend:${BUILD_NUMBER} .'
            }
        }
        stage ("Push to ECR") {
            agent {
                docker {
                    image 'public.ecr.aws/p1i4w9x2/jenkins/aws-agents:latest'
                    args '--entrypoint="" -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                cleanWs()
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'educacionit'
                ]]) {
                    sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 781013578291.dkr.ecr.us-east-1.amazonaws.com'
                    sh "docker push 781013578291.dkr.ecr.us-east-1.amazonaws.com/curso-edit-backend:${BUILD_NUMBER}"
                }
            }
        }
    }
}
