services:
  frontend:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    image: 781013578291.dkr.ecr.us-east-1.amazonaws.com/curso-edit-backend:latest
    #build:
      #context: ./backend
      #dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - "3000:3001"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge  
